name:                imageflagger
version:             0.1.0.0
github:              "roridev/imageflagger"
license:             BSD3
author:              "roridev"
maintainer:          "t3ctotalmenterandom1@outlook.com"
copyright:           "roridev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/roridev/imageflagger#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src/core
  dependencies:
  - containers
  - bytestring
  - base16-bytestring >= 1.0
  - mtl
  - cryptohash
  - directory
  